### PR TITLE
Fix `tapParser` reference errors by not relying on resolving a global variable.

### PR DESCRIPTION
**Pull request by marques-work**
Build `tap-parser` into adapter to create a monolithic bundle to avoid reference errors to `tapParser`.

@bySabi This is still happening in `4.1.3` (I'm using karma-tap + webpack + tape). I had similar issues with your `carma-tap-webpack` template.

This was the most straightforward, general, and reliable solution that I could come up with. I've also injected `babel-polyfill` to ensure it runs in phantomjs as well.

Please let me know what you think, and if you are alright with this PR, could you merge, version bump to 4.1.4, and publish?

Thanks!

### CODE REVIEW

**Comment by marques-work** [comment]
@bySabi I'd like to point out that the travis config won't work for node v4; the build is broken on node v4 because the `beforeInstall` steps include:

> npm i -g npm@latest

Which throws errors because npm 6.0.0 uses language constructs that aren't supported in node v4.

Same goes for the appveyor build. node 4 fails for the same reason. I'd suggest to either remove that build step (the one that upgrades npm) or drop support for node 4.

**Comment by bySabi** [comment]
@marques-work your PR is good to me.
Thanks for take the time to test and fix the edge cases 👏

I will make some little changes before publish `4.1.4`

**Comment by bySabi** [comment]
published 4.1.4

`node 4` CI settings is working again.
 
Two questions. 

Do you have any issue with npm tool that's choose yarn? 

In what case `babel-polyfill` is needed with the `adapter`?

**Comment by marques-work** [comment]
@bySabi Hi there, thanks for the quick merge!

> Do you have any issue with npm tool that's choose yarn?

The issues were related to the Travis/AppVeyor builds. Prior to this change, we were doing `npm i npm@latest -g` for every build. This works for most node versions except for `node v4` as `npm 6.0.0` seems to be incompatible.

When I dropped the line to install the latest `npm` the AppVeyor build had issues with the old `npm` version. Travis was fine, sort of "by accident" because I had a `yarn.lock` file, which caused Travis to choose `yarn` for the build instead of `npm`. The build went green. So instead of trying to find that magical `npm` version that worked for everything, I decided to make appveyor build with `yarn` because Travis already proved that it would work. As it too worked for AppVeyor on all supported `node` versions, I just stuck with it.

> In what case `babel-polyfill` is needed with the `adapter`?

Even after processing with `babel` + `env` preset, some ES6 features were still making out to the `adapter`, noticeably `Symbol`. This works fine in Chrome or FF, but it fails in PhantomJS, as this browser only supports ES5, yet is still in use by many CI/CD environments. So rather than trying to coerce (and figure out how) `babel` to convert `Symbol` into some ES5 equivalent, I just chose `babel-polyfill` (which is probably what `babel` would have done anyway under the hood if I could figure out the right config).

Does that answer your questions?

**Comment by bySabi** [comment]
Yes!!, now is clear to me 😃

was a pleasure review your PR. 👍 

Will be in touch

**Pull request merged**
