### PR TITLE
remove tap-finished dependency

### PR DESCRIPTION
**Pull request by bySabi**
Hi @tmcw  review this PR.
- updated tap-parser to latest
- remove tap-finished dependency
- minor cleanups on test settings and Doc

Thanks!

### CODE REVIEW

**Comment by tmcw** [comment]
👍 thx!

**Comment by bySabi** [comment]
@tmcw README need a  `new line` on `top contributors` part.

And don´t forget publish a new npm when you can.

**Comment by tmcw** [comment]
@bySabi do you want to adopt this project? i'd be happy to transfer ownership to you

**Comment by bySabi** [comment]
@tmcw my english is not very good but I will try to do my best.
Give me the ownership of it

**Comment by tmcw** [comment]
Great! It looks like you have a fork locally, if you've got all your changes merged up, can you delete it so that I can request a transfer?

**Comment by bySabi** [comment]
@tmcw I remove my karma-tap fork.

**Pull request merged**
